<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./views/css/style.css">
    <title>Aim-trainnig</title>
</head>
<body>
    <header>
        <span>Aim training</span>
    </header>
    <main>
        <div id="app">
            <h2>Click on all the targets before end</h2>
            <canvas id="canvx" height="470" width="1140"></canvas>
        </div>
        <div id="box_board">
            <div id="timer"><span>00:00</span></div>
            <div id="score"><span>0</span></div>
            <button id="start">Start Game</button>
        </div>
    </main>
    <script type="module" src="./views/js/main.js"></script>
</body>
</html>